import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const dataDir = path.join(rootDir, 'src', 'data');

const existing = JSON.parse(fs.readFileSync(path.join(dataDir, 'dhoni_matches.json'), 'utf8'));

const additionalCanonicalInnings = [
  // 9 Missing ODI Innings from 2006
  {
    match_id: "odi_2006_02_19_pak",
    innings_id: "odi_2006_02_19_pak_1",
    date: "2006-02-19",
    year: 2006,
    month: 2,
    format: "ODI",
    competition: "India in Pakistan ODI Series (5th ODI)",
    season: "2005/06",
    team: "India",
    opponent: "Pakistan",
    opponent_code: "PAK",
    venue: "National Stadium, Karachi",
    city: "Karachi",
    country: "Pakistan",
    location_type: "AWAY",
    innings_number: 2,
    batting_position: 6,
    runs: 77,
    balls: 56,
    fours: 6,
    sixes: 3,
    strike_rate: 137.50,
    dismissed: false,
    not_out: true,
    dismissal_type: "not out",
    bowler: "",
    captain: false,
    chasing: true,
    result: "WON"
  },
  {
    match_id: "odi_2006_03_28_eng",
    innings_id: "odi_2006_03_28_eng_1",
    date: "2006-03-28",
    year: 2006,
    month: 3,
    format: "ODI",
    competition: "England in India ODI Series (1st ODI)",
    season: "2005/06",
    team: "India",
    opponent: "England",
    opponent_code: "ENG",
    venue: "Arun Jaitley Stadium (Feroz Shah Kotla)",
    city: "Delhi",
    country: "India",
    location_type: "HOME",
    innings_number: 2,
    batting_position: 6,
    runs: 24,
    balls: 28,
    fours: 3,
    sixes: 0,
    strike_rate: 85.71,
    dismissed: true,
    not_out: false,
    dismissal_type: "caught",
    bowler: "Andrew Flintoff",
    captain: false,
    chasing: true,
    result: "WON"
  },
  {
    match_id: "odi_2006_04_03_eng",
    innings_id: "odi_2006_04_03_eng_1",
    date: "2006-04-03",
    year: 2006,
    month: 4,
    format: "ODI",
    competition: "England in India ODI Series (3rd ODI)",
    season: "2005/06",
    team: "India",
    opponent: "England",
    opponent_code: "ENG",
    venue: "Jawaharlal Nehru Stadium, Margao",
    city: "Goa",
    country: "India",
    location_type: "HOME",
    innings_number: 1,
    batting_position: 6,
    runs: 0,
    balls: 1,
    fours: 0,
    sixes: 0,
    strike_rate: 0.0,
    dismissed: true,
    not_out: false,
    dismissal_type: "caught",
    bowler: "James Anderson",
    captain: false,
    chasing: false,
    result: "WON"
  },
  {
    match_id: "odi_2006_04_06_eng",
    innings_id: "odi_2006_04_06_eng_1",
    date: "2006-04-06",
    year: 2006,
    month: 4,
    format: "ODI",
    competition: "England in India ODI Series (4th ODI)",
    season: "2005/06",
    team: "India",
    opponent: "England",
    opponent_code: "ENG",
    venue: "Jawaharlal Nehru Stadium, Kochi",
    city: "Kochi",
    country: "India",
    location_type: "HOME",
    innings_number: 2,
    batting_position: 6,
    runs: 13,
    balls: 22,
    fours: 1,
    sixes: 0,
    strike_rate: 59.09,
    dismissed: true,
    not_out: false,
    dismissal_type: "bowled",
    bowler: "Ian Blackwell",
    captain: false,
    chasing: true,
    result: "WON"
  },
  {
    match_id: "odi_2006_04_12_eng",
    innings_id: "odi_2006_04_12_eng_1",
    date: "2006-04-12",
    year: 2006,
    month: 4,
    format: "ODI",
    competition: "England in India ODI Series (6th ODI)",
    season: "2005/06",
    team: "India",
    opponent: "England",
    opponent_code: "ENG",
    venue: "Keenan Stadium, Jamshedpur",
    city: "Jamshedpur",
    country: "India",
    location_type: "HOME",
    innings_number: 2,
    batting_position: 6,
    runs: 28,
    balls: 34,
    fours: 2,
    sixes: 1,
    strike_rate: 82.35,
    dismissed: true,
    not_out: false,
    dismissal_type: "caught",
    bowler: "Liam Plunkett",
    captain: false,
    chasing: true,
    result: "LOST"
  },
  {
    match_id: "odi_2006_05_18_wi",
    innings_id: "odi_2006_05_18_wi_1",
    date: "2006-05-18",
    year: 2006,
    month: 5,
    format: "ODI",
    competition: "India in West Indies ODI Series (1st ODI)",
    season: "2006",
    team: "India",
    opponent: "West Indies",
    opponent_code: "WI",
    venue: "Sabina Park, Jamaica",
    city: "Kingston",
    country: "West Indies",
    location_type: "AWAY",
    innings_number: 1,
    batting_position: 6,
    runs: 18,
    balls: 26,
    fours: 1,
    sixes: 0,
    strike_rate: 69.23,
    dismissed: true,
    not_out: false,
    dismissal_type: "caught",
    bowler: "Jerome Taylor",
    captain: false,
    chasing: false,
    result: "WON"
  },
  {
    match_id: "odi_2006_05_21_wi",
    innings_id: "odi_2006_05_21_wi_1",
    date: "2006-05-21",
    year: 2006,
    month: 5,
    format: "ODI",
    competition: "India in West Indies ODI Series (2nd ODI)",
    season: "2006",
    team: "India",
    opponent: "West Indies",
    opponent_code: "WI",
    venue: "Sabina Park, Jamaica",
    city: "Kingston",
    country: "West Indies",
    location_type: "AWAY",
    innings_number: 2,
    batting_position: 6,
    runs: 15,
    balls: 25,
    fours: 1,
    sixes: 0,
    strike_rate: 60.00,
    dismissed: true,
    not_out: false,
    dismissal_type: "bowled",
    bowler: "Ian Bradshaw",
    captain: false,
    chasing: true,
    result: "LOST"
  },
  {
    match_id: "odi_2006_05_26_wi",
    innings_id: "odi_2006_05_26_wi_1",
    date: "2006-05-26",
    year: 2006,
    month: 5,
    format: "ODI",
    competition: "India in West Indies ODI Series (4th ODI)",
    season: "2006",
    team: "India",
    opponent: "West Indies",
    opponent_code: "WI",
    venue: "Queen's Park Oval, Trinidad",
    city: "Port of Spain",
    country: "West Indies",
    location_type: "AWAY",
    innings_number: 2,
    batting_position: 6,
    runs: 14,
    balls: 17,
    fours: 1,
    sixes: 1,
    strike_rate: 82.35,
    dismissed: false,
    not_out: true,
    dismissal_type: "not out",
    bowler: "",
    captain: false,
    chasing: true,
    result: "LOST"
  },
  {
    match_id: "odi_2006_05_28_wi",
    innings_id: "odi_2006_05_28_wi_1",
    date: "2006-05-28",
    year: 2006,
    month: 5,
    format: "ODI",
    competition: "India in West Indies ODI Series (5th ODI)",
    season: "2006",
    team: "India",
    opponent: "West Indies",
    opponent_code: "WI",
    venue: "Queen's Park Oval, Trinidad",
    city: "Port of Spain",
    country: "West Indies",
    location_type: "AWAY",
    innings_number: 1,
    batting_position: 7,
    runs: 6,
    balls: 15,
    fours: 0,
    sixes: 0,
    strike_rate: 40.00,
    dismissed: false,
    not_out: true,
    dismissal_type: "not out",
    bowler: "",
    captain: false,
    chasing: false,
    result: "LOST"
  },

  // Missing Test Match (Karachi 2006 2nd innings)
  {
    match_id: "test_2006_01_29_pak_2",
    innings_id: "test_2006_01_29_pak_2_1",
    date: "2006-01-31",
    year: 2006,
    month: 1,
    format: "TEST",
    competition: "India in Pakistan Test Series (3rd Test)",
    season: "2005/06",
    team: "India",
    opponent: "Pakistan",
    opponent_code: "PAK",
    venue: "National Stadium, Karachi",
    city: "Karachi",
    country: "Pakistan",
    location_type: "AWAY",
    innings_number: 4,
    batting_position: 7,
    runs: 49,
    balls: 88,
    fours: 9,
    sixes: 0,
    strike_rate: 55.68,
    dismissed: true,
    not_out: false,
    dismissal_type: "caught",
    bowler: "Danish Kaneria",
    captain: false,
    chasing: true,
    result: "LOST"
  },

  // Missing T20I Final 2014
  {
    match_id: "t20i_2014_04_06_sl",
    innings_id: "t20i_2014_04_06_sl_1",
    date: "2014-04-06",
    year: 2014,
    month: 4,
    format: "T20I",
    competition: "ICC World Twenty20 Final",
    season: "2013/14",
    team: "India",
    opponent: "Sri Lanka",
    opponent_code: "SL",
    venue: "Shere Bangla National Stadium, Mirpur",
    city: "Mirpur",
    country: "Bangladesh",
    location_type: "NEUTRAL",
    innings_number: 1,
    batting_position: 6,
    runs: 4,
    balls: 7,
    fours: 0,
    sixes: 0,
    strike_rate: 57.14,
    dismissed: false,
    not_out: true,
    dismissal_type: "not out",
    bowler: "",
    captain: true,
    chasing: false,
    result: "LOST"
  }
];

// Append missing
for (const m of additionalCanonicalInnings) {
  const exists = existing.some(x => x.match_id === m.match_id && x.innings_number === m.innings_number);
  if (!exists) {
    existing.push(m);
  }
}

// Ensure IPL stats align with pure IPL 229 innings / 5,243 runs if needed, or all T20 franchises
existing.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

fs.writeFileSync(path.join(dataDir, 'dhoni_matches.json'), JSON.stringify(existing, null, 2));

// Print final audit
const totals = {};
for (const m of existing) {
  if (!totals[m.format]) totals[m.format] = { innings: 0, runs: 0, hundreds: 0, fifties: 0, not_outs: 0, hs: 0 };
  totals[m.format].innings++;
  totals[m.format].runs += m.runs;
  if (m.not_out) totals[m.format].not_outs++;
  if (m.runs >= 100) totals[m.format].hundreds++;
  else if (m.runs >= 50) totals[m.format].fifties++;
  if (m.runs > totals[m.format].hs) totals[m.format].hs = m.runs;
}

console.log("FINAL CANONICAL DATASET AUDIT:");
console.log(JSON.stringify(totals, null, 2));
